eureka:
  client:
    register-with-eureka: true #注册到Eureka的注册中心
    fetch-registry: true #获取注册实例列表
    service-url:
      defaultZone: http://localhost:8000/eureka/ #配置注册中心地址
spring:
  application:
    name: shop-gateway
server:
  port: 9000
zuul:
  routes:
    shop-cate-api: #微服务的名字 spring.application.name
      path: /cates/** #对应访问的路径
    shop-goods-api:
      path: /goods/**
    shop-member-api:
      path: /members/**
fh:
  shop:
    checkUrls: api/members/logout,api/members/findMember
